### ISSUE TITLE
What is the meaning of proj_value_stu?

### ISSUE THREAD

**Issue by anitaweng** [DefangChen/SemCKD#3]
Hi,
I want to know the meaning of [proj_value_stu](https://github.com/DefangChen/SemCKD/blob/c07f4df43f813fdad2fdecbbcaadf19a59513b32/models/util.py#L119).
I have printed the value out, but I only found out that the output will be the same dimension as teacher layers, and will have multiple elements, the number of duplicated-shape features which is related to the number of student layers.

**Comment by DefangChen** [comment]
We project the original student feature maps into the dimension of the associated teacher feature maps, such that they can be compared with a MSE distance. 

Note that the original student feature maps and teacher feature maps may have different dimensions.

**Comment by anitaweng** [comment]
Got it! Thanks a lot.
